apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zomato-app-ingress
  namespace: zomato-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"        # Redirect HTTP to HTTPS
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret-type: 
    nginx.ingress.kubernetes.io/auth-secret: my-secret
spec:
  rules:
  - host: zomato.example.com     # Hostname-based routing
    http:
      paths:
      - path: /static                # Path-based routing
        pathType: Prefix
        backend:
          service:
            name: zomato-api-service
            port:
              number: 80
      - path: /app                # Another path routing
        pathType: Prefix
        backend:
          service:
            name: zomato-web-service
            port:
              number: 80
  tls:
  - hosts:
    - zomato.example.com
    secretName: zomato-tls-secret  # The TLS Secret containing certificate and key
